# Generated by Django 4.1.4 on 2023-01-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_portfolio_staff_portfolio_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
