# Generated by Django 4.1.6 on 2023-02-11 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_portfolio_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='organization',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='product',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='room',
            name='authority_portfolio',
        ),
        migrations.AddField(
            model_name='room',
            name='authority_portfolio',
            field=models.ManyToManyField(to='core.portfolio'),
        ),
    ]
